# Generated by Django 4.1.7 on 2023-03-26 22:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('scrumMaster', models.CharField(max_length=100)),
                ('productOwner', models.CharField(max_length=100)),
                ('developers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, default=list, size=None)),
                ('startDate', models.DateField()),
                ('Methodology', models.CharField(choices=[('Undecided', 'Undecided'), ('Agile', 'Agile'), ('Waterfall', 'Waterfall')], default='Undecided', max_length=100)),
            ],
        ),
    ]
