# Generated by Django 4.1.7 on 2023-03-26 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productOwner', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('Methodology', models.CharField(choices=[('Undecided', 'Undecided'), ('Agile', 'Agile'), ('Waterfall', 'Waterfall')], default='Undecided', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Developers',
            new_name='Developer',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='product',
            name='developers',
            field=models.ManyToManyField(to='myapi.developer'),
        ),
        migrations.AddField(
            model_name='product',
            name='scrumMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.scrummaster'),
        ),
    ]
